spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/test
    username: h2
    password: h2
    driverClassName: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true


server:
  port: 8080
  error:
    whitelabel:
      enabled: false

